#!/usr/bin/env bash
# 
# usage: ./download_checked <hash> <download url>
#
# Downloads a given URL and verifies if the sha256 of downloaded file matches the input hash

set -eufo pipefail

file="$(mktemp)"
curl -sSL "$2" > "$file"
hash="$(sha256sum "$file" | head -c 64)"
if [ "$hash" != "$1" ]; then
	echo "invalid sha256sum" >&2
	rm "$file"
	exit 1
fi
echo "$file"
